Repository codesquad-member-2020/baseball-10, pull requests merged in 2020-05, with the labels that each got.

#7 Feature/fe router
  FE/baseball/src/App.js
  FE/baseball/src/components/gamelist/GameList.jsx
  FE/baseball/src/components/login/Login.jsx
  FE/baseball/src/components/playground/PlayGround.jsx
  FE/baseball/src/index.js
Labels: FE, React

#10 Feature/fe project structure
  FE/baseball/.env
  FE/baseball/.prettierrc.json
  FE/baseball/package-lock.json
  FE/baseball/package.json
  FE/baseball/public/index.html
  FE/baseball/src/App.jsx
  FE/baseball/src/action/action.jsx
  FE/baseball/src/assets/background.png
  FE/baseball/src/assets/codesquad.png
  FE/baseball/src/assets/github.svg
  FE/baseball/src/assets/logo.svg
  FE/baseball/src/components/BaseballProvider.jsx
  FE/baseball/src/components/gamelist/GameList.jsx
  FE/baseball/src/components/login/Login.jsx
  FE/baseball/src/context/context.jsx
  FE/baseball/src/index.jsx
  FE/baseball/src/mock/baseballData.js
  FE/baseball/src/reducer/reducer.jsx
  FE/baseball/src/serviceWorker.jsx
  FE/baseball/src/setupTests.jsx
  FE/baseball/src/style/Background.jsx
  FE/baseball/src/style/Button.jsx
  FE/baseball/src/style/GlobalStyle.jsx
Labels: FE, React, Styled-Component

#19 Feature/fe playerlist
  FE/baseball/src/App.jsx
  FE/baseball/src/components/playground/PlayGround.jsx
  FE/baseball/src/components/playground/playerList/Header.jsx
  FE/baseball/src/components/playground/playerList/PlayerCard.jsx
  FE/baseball/src/components/playground/playerList/PlayerList.jsx
  FE/baseball/src/components/playground/playerList/PlayerListCard.jsx
  FE/baseball/src/components/playground/playerList/TotalCard.jsx
  FE/baseball/src/store/baseballStore.js
Labels: FE, React

#20 [#9] Style: 코드 인벤션 수정, 모달 스타일 변수 수정
  FE/baseball/src/components/Modal.jsx
  FE/baseball/src/components/teamList/TeamList.jsx
  FE/baseball/src/style/GlobalStyle.jsx
Labels: FE

#22 [FE] 게임 로딩 화면 구현
  FE/baseball/src/App.jsx
  FE/baseball/src/assets/magnify.svg
  FE/baseball/src/components/Modal.jsx
  FE/baseball/src/components/NotFoundPage.jsx
  FE/baseball/src/components/loading/Loading.jsx
  FE/baseball/src/components/loading/PlayerCard.jsx
  FE/baseball/src/components/login/Login.jsx
  FE/baseball/src/components/playground/playerList/PlayerCard.jsx
  FE/baseball/src/components/playground/playerList/PlayerList.jsx
  FE/baseball/src/components/playground/playerList/PlayerListCard.jsx
  FE/baseball/src/components/teamList/TeamList.jsx
  FE/baseball/src/store/baseballStore.js
  FE/baseball/src/style/Animation.jsx
  FE/baseball/src/style/Cover.jsx
  FE/baseball/src/style/GlobalStyle.jsx
Labels: FE, enhancement

#24 Feature/fe playground
  FE/baseball/src/components/playground/CurrentPlayer.jsx
  FE/baseball/src/components/playground/GameArea.jsx
  FE/baseball/src/components/playground/PlayGround.jsx
  FE/baseball/src/components/playground/ScoreBoard.jsx
  FE/baseball/src/components/playground/TeamScores.jsx
  FE/baseball/src/components/playground/playerList/PlayerCard.jsx
  FE/baseball/src/store/baseballStore.js
  FE/baseball/src/style/GlobalStyle.jsx
Labels: FE

#26 Feature/fe playground
  FE/baseball/.env
  FE/baseball/.prettierrc.json
  FE/baseball/package-lock.json
  FE/baseball/package.json
  FE/baseball/public/index.html
  FE/baseball/src/App.js
  FE/baseball/src/App.jsx
  FE/baseball/src/action/action.jsx
  FE/baseball/src/assets/background.png
  FE/baseball/src/assets/github.svg
  FE/baseball/src/assets/logo.svg
  FE/baseball/src/assets/magnify.svg
  FE/baseball/src/components/BaseballProvider.jsx
  FE/baseball/src/components/Modal.jsx
  FE/baseball/src/components/NotFoundPage.jsx
  FE/baseball/src/components/loading/Loading.jsx
  FE/baseball/src/components/loading/PlayerCard.jsx
  FE/baseball/src/components/login/Login.jsx
  FE/baseball/src/components/playground/BatterHistorys.jsx
  FE/baseball/src/components/playground/CurrentPlayer.jsx
  FE/baseball/src/components/playground/GameArea.jsx
  FE/baseball/src/components/playground/PlayGround.jsx
  FE/baseball/src/components/playground/ScoreBoard.jsx
  FE/baseball/src/components/playground/StatsCenter.jsx
  FE/baseball/src/components/playground/TeamScores.jsx
  FE/baseball/src/components/playground/playerList/Header.jsx
  FE/baseball/src/components/playground/playerList/PlayerCard.jsx
  FE/baseball/src/components/playground/playerList/PlayerList.jsx
  FE/baseball/src/components/playground/playerList/PlayerListCard.jsx
  FE/baseball/src/components/playground/playerList/TotalCard.jsx
  FE/baseball/src/components/teamList/Header.jsx
  FE/baseball/src/components/teamList/Loading.jsx
  FE/baseball/src/components/teamList/TeamCard.jsx
  FE/baseball/src/components/teamList/TeamList.jsx
  FE/baseball/src/components/useFetch.jsx
  FE/baseball/src/context/context.jsx
  FE/baseball/src/index.jsx
  FE/baseball/src/reducer/reducer.jsx
  FE/baseball/src/serviceWorker.jsx
  FE/baseball/src/setupTests.jsx
  FE/baseball/src/store/baseballStore.js
  FE/baseball/src/style/Animation.jsx
  FE/baseball/src/style/Background.jsx
  FE/baseball/src/style/Button.jsx
  FE/baseball/src/style/Cover.jsx
  FE/baseball/src/style/GlobalStyle.jsx
  FE/baseball/src/util/util.js
  FE/baseball/yarn.lock
Labels: FE

#28 Feature/fe playground
  FE/baseball/src/components/playground/BatterHistorys.jsx
  FE/baseball/src/components/playground/CurrentPlayer.jsx
  FE/baseball/src/components/playground/GameArea.jsx
  FE/baseball/src/components/playground/PlayGround.jsx
  FE/baseball/src/components/playground/ScoreBoard.jsx
  FE/baseball/src/components/playground/StatsCenter.jsx
  FE/baseball/src/components/playground/TeamScores.jsx
  FE/baseball/src/store/baseballStore.js
Labels: FE

#29 [FE] 게임 보드 진행 사항 머지
  FE/baseball/src/assets/appearing.png
  FE/baseball/src/assets/idle.png
  FE/baseball/src/assets/idle_away.png
  FE/baseball/src/assets/idle_home.png
  FE/baseball/src/assets/run.png
  FE/baseball/src/assets/run_away.png
  FE/baseball/src/assets/run_home.png
  FE/baseball/src/components/playground/GameArea.jsx
  FE/baseball/src/components/playground/PlayGround.jsx
  FE/baseball/src/components/playground/gameboard/Character.jsx
  FE/baseball/src/components/playground/gameboard/GameBoard.jsx
  FE/baseball/src/components/playground/gameboard/GameCanvas.jsx
  FE/baseball/src/components/teamList/Loading.jsx
  FE/baseball/src/store/baseballStore.js
  FE/baseball/src/style/Animation.jsx
  FE/baseball/src/style/GlobalStyle.jsx
Labels: FE

#31 [FE] 캔버스 비율 수정
  FE/baseball/src/components/Modal.jsx
  FE/baseball/src/components/playground/CurrentPlayer.jsx
  FE/baseball/src/components/playground/StatsCenter.jsx
  FE/baseball/src/components/playground/gameboard/Character.jsx
  FE/baseball/src/components/playground/gameboard/GameBoard.jsx
  FE/baseball/src/components/playground/gameboard/GameCanvas.jsx
Labels: FE

#33 FE 진행사항 머지용 풀 리퀘스트
  FE/baseball/.env
  FE/baseball/package.json
  FE/baseball/src/App.jsx
  FE/baseball/src/action/action.jsx
  FE/baseball/src/components/OAuth/OAuth.jsx
  FE/baseball/src/components/loading/Loading.jsx
  FE/baseball/src/components/login/Login.jsx
  FE/baseball/src/components/playground/GameArea.jsx
  FE/baseball/src/components/playground/PlayGround.jsx
  FE/baseball/src/components/playground/TeamScores.jsx
  FE/baseball/src/components/playground/gameboard/Character.jsx
  FE/baseball/src/components/playground/gameboard/GameBoard.jsx
  FE/baseball/src/components/playground/playerList/PlayerList.jsx
  FE/baseball/src/components/playground/playerList/PlayerListCard.jsx
  FE/baseball/src/components/useFetch.jsx
  FE/baseball/src/reducer/reducer.jsx
  FE/baseball/src/store/baseballStore.js
  FE/baseball/src/util/util.js
  FE/baseball/yarn.lock
Labels: FE

#34 [FE] 게임 보드판 구현 완료
  FE/baseball/src/components/playground/PlayGround.jsx
  FE/baseball/src/components/playground/gameboard/Character.jsx
  FE/baseball/src/components/playground/gameboard/GameBoard.jsx
  FE/baseball/src/constants/constants.js
  FE/baseball/src/reducer/reducer.jsx
  FE/baseball/src/store/baseballStore.js
  FE/baseball/src/style/Animation.jsx
Labels: FE, enhancement

#36 Feature/fe-playground
  FE/baseball/.env
  FE/baseball/src/App.jsx
  FE/baseball/src/action/action.jsx
  FE/baseball/src/components/playerList/Header.jsx
  FE/baseball/src/components/playerList/PlayerCard.jsx
  FE/baseball/src/components/playerList/PlayerList.jsx
  FE/baseball/src/components/playerList/PlayerListCard.jsx
  FE/baseball/src/components/playerList/TotalCard.jsx
  FE/baseball/src/components/playground/BatterHistorys.jsx
  FE/baseball/src/components/playground/GameArea.jsx
  FE/baseball/src/components/playground/PlayGround.jsx
  FE/baseball/src/components/playground/gameboard/GameBoard.jsx
  FE/baseball/src/components/useFetch.jsx
  FE/baseball/src/reducer/reducer.jsx
  FE/baseball/src/store/baseballStore.js
  FE/baseball/src/util/util.js
Labels: FE

#38 [FE] 팀 리스트 패치
  FE/baseball/src/components/playground/PlayGround.jsx
  FE/baseball/src/components/teamList/TeamList.jsx
  FE/baseball/src/components/useFetch.jsx
  FE/baseball/src/reducer/reducer.jsx
  FE/baseball/src/store/baseballStore.js
Labels: FE
